language: node_js
node_js:
- v6
- v8
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
  - secure: Bg08bmtZxlt18xVd7IT3Ft8rC8Cd3iT2txSqoFKaUERu2FzlaPvi+DS5K0SeOqAB9LfyRST/Msdg+jmPEvQ/0VXa2lfhqf31YSrXStnd9h1Owxr53KPV3O6FX1mfH8RlmHVDosKUR6mJeiush4MSEFPCmB1VBTwpyRcbBt3sbJ0=
  - secure: M4PJdQwYF0dWq+/bMhz4WTRhiKnDuuvgwLImzGQQ0I5zEz6yQofUVmXsAdYkqTvhr8klO+XQktzq62wsWADIe1eb5Vlym87rZweA1MmhzhpfSgYSwQ9IdpVXRbqFVB7HbqrGTHqOSfGOu27e8z4RNg8h3EXCiTnN1qHyY0N5vrI=
script: xvfb-run npm test -- --browsers Firefox --single-run
deploy:
  provider: npm
  email: irfs@bbc.co.uk
  skip_cleanup: true
  api_key:
    secure: cSuf3iiNYM2jSjrk7xNxVLuZn+7S78jktze5MyFdK0rchgOessLY0yIDF9MZbhVbCXGgVbygp+dP5IMHPIDFCqC77WyaWCKdRfretb//RoiRAkEL9B6j8kJ//Sl7LPZ5yYpzotC2tF8zDrw0cucz1sXDTRN9x0C1do2O83hS/qk=
  on:
    tags: true
    repo: bbc/peaks.js
